'@type': "SoftwareComponentType"
createdDate: "2018-10-10T04:53:05.614Z"
lastUpdated: "2018-10-10T04:53:06.035Z"
id: "Software.DemoAppApplication"
name: "Demo App Application"
description: "Installs and configures the Demo App Application Server"
publishStatus: "PUBLISHED"
publishStatusName: "Published"
schema:
  fields:
  - id: "demo_app_mysql_server"
    label: "demo_app_mysql_server"
    description: ""
    dataType:
      type: "primitive"
      typeId: "STRING"
    state:
      dependencies: []
      facets:
      - type: "defaultValue"
        value:
          type: "constant"
          value:
            type: "string"
            value: ""
      - type: "mandatory"
        value:
          type: "constant"
          value:
            type: "boolean"
            value: true
    isMultiValued: false
  - id: "demo_app_mysql_user"
    label: "demo_app_mysql_user"
    description: ""
    dataType:
      type: "primitive"
      typeId: "STRING"
    state:
      dependencies: []
      facets:
      - type: "defaultValue"
        value:
          type: "constant"
          value:
            type: "string"
            value: ""
      - type: "mandatory"
        value:
          type: "constant"
          value:
            type: "boolean"
            value: true
    isMultiValued: false
  - id: "demo_app_mysql_password"
    label: "demo_app_mysql_password"
    description: ""
    dataType:
      type: "primitive"
      typeId: "STRING"
    state:
      dependencies: []
      facets:
      - type: "defaultValue"
        value:
          type: "constant"
          value:
            type: "string"
            value: ""
      - type: "mandatory"
        value:
          type: "constant"
          value:
            type: "boolean"
            value: true
    isMultiValued: false
  - id: "demo_app_mysql_database"
    label: "demo_app_mysql_database"
    description: ""
    dataType:
      type: "primitive"
      typeId: "STRING"
    state:
      dependencies: []
      facets:
      - type: "defaultValue"
        value:
          type: "constant"
          value:
            type: "string"
            value: ""
      - type: "mandatory"
        value:
          type: "constant"
          value:
            type: "boolean"
            value: true
    isMultiValued: false
  - id: "host"
    label: "Container"
    description: ""
    dataType:
      type: "ref"
      componentTypeId: "com.vmware.csp.iaas.blueprint.service"
      classId: "Infrastructure.Machine.Schema"
      label: "Machine"
    state:
      dependencies: []
      facets:
      - type: "visible"
        value:
          type: "constantClause"
          value:
            type: "boolean"
            value: false
      - type: "mandatory"
        value:
          type: "constant"
          value:
            type: "boolean"
            value: true
      - type: "internal"
        value:
          type: "constantClause"
          value:
            type: "boolean"
            value: true
    isMultiValued: false
containerFieldId: "host"
lifecycleTasks:
- createdDate: "2018-10-10T04:53:05.618Z"
  lastUpdated: "2018-10-11T12:29:21.894Z"
  script:
    scriptContent: "#!/bin/bash\n#eros add this - start\nexport PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin:/root/bin\n\
      #eros add this - end\n# Download and install Demo app\n/usr/bin/wget -O /var/www/html/config.php\
      \ https://raw.githubusercontent.com/serosagon/crmapp/master/app/config.php\n\
      /usr/bin/wget -O /var/www/html/create.php https://raw.githubusercontent.com/serosagon/crmapp/master/app/create.php\n\
      /usr/bin/wget -O /var/www/html/delete.php https://raw.githubusercontent.com/serosagon/crmapp/master/app/delete.php\n\
      /usr/bin/wget -O /var/www/html/error.php https://raw.githubusercontent.com/serosagon/crmapp/master/app/error.php\n\
      /usr/bin/wget -O /var/www/html/index.php https://raw.githubusercontent.com/serosagon/crmapp/master/app/index.php\n\
      /usr/bin/wget -O /var/www/html/read.php https://raw.githubusercontent.com/serosagon/crmapp/master/app/read.php\n\
      /usr/bin/wget -O /var/www/html/update.php https://raw.githubusercontent.com/serosagon/crmapp/master/app/update.php\n\
      # Configure the Demo App\n#/usr/bin/sed -i \"s@DBName@$demo_app_mysql_database@\"\
      \ /var/www/html/config.php\n#/usr/bin/sed -i \"s@DBUser@$demo_app_mysql_user@\"\
      \ /var/www/html/config.php\n#/usr/bin/sed -i \"s@DBPassword@$demo_app_mysql_password@\"\
      \ /var/www/html/config.php\n#/usr/bin/sed -i \"s@DBServer@$demo_app_mysql_server@\"\
      \ /var/www/html/config.php\n/bin/sed -i \"s@DBName@$demo_app_mysql_database@\"\
      \ /var/www/html/config.php\n/bin/sed -i \"s@DBUser@$demo_app_mysql_user@\" /var/www/html/config.php\n\
      /bin/sed -i \"s@DBPassword@$demo_app_mysql_password@\" /var/www/html/config.php\n\
      /bin/sed -i \"s@DBServer@$demo_app_mysql_server@\" /var/www/html/config.php\n\
      \n# Download and run the DB script\n/usr/bin/wget -O /tmp/employees.sql https://raw.githubusercontent.com/serosagon/crmapp/master/app/employees.sql\n\
      /usr/bin/mysql -u \"$demo_app_mysql_user\" -p\"$demo_app_mysql_password\" demo\
      \ -h $demo_app_mysql_server < /tmp/employees.sql\n# Configure and start Apache\n\
      #/usr/bin/sed -i \"/^<Directory \\\"\\/var\\/www\\/html\\\">/,/^<\\/Directory>/{s/AllowOverride\
      \ None/AllowOverride All/g}\" /etc/httpd/conf/httpd.conf\n#/usr/bin/sed -i \"\
      s@Listen 80@Listen 8080@\" /etc/httpd/conf/httpd.conf\n/bin/sed -i \"/^<Directory\
      \ \\\"\\/var\\/www\\/html\\\">/,/^<\\/Directory>/{s/AllowOverride None/AllowOverride\
      \ All/g}\" /etc/httpd/conf/httpd.conf\n/bin/sed -i \"s@Listen 80@Listen 8080@\"\
      \ /etc/httpd/conf/httpd.conf\n#eros add this - start\n#/usr/bin/systemctl enable\
      \ httpd.service\n#/usr/bin/systemctl start httpd.service\nservice httpd start\n\
      # Open http firewall for remote connections\n#/usr/bin/firewall-cmd --permanent\
      \ --zone=public --add-port=8080/tcp\n#/usr/bin/firewall-cmd --reload\n#eros\
      \ add this - end\n# Configure SELinux to allow remote DB connection\n#/usr/sbin/setsebool\
      \ httpd_can_network_connect_db on -P"
    isRebootAfter: false
    scriptTypeId: "Bash"
  taskDescriptorRef:
    id: "CONFIGURE"
    label: "Configure"
- createdDate: "2018-10-10T04:53:05.617Z"
  lastUpdated: "2018-10-11T12:29:21.894Z"
  script:
    scriptContent: "#!/bin/bash\n# Install Apache and PHP\n/usr/bin/yum -y install\
      \ mysql httpd php php-mysqlnd php-common php-gd php-xml php-mbstring php-mcrypt\
      \ php-xmlrpc unzip wget\n"
    isRebootAfter: false
    scriptTypeId: "Bash"
  taskDescriptorRef:
    id: "INSTALL"
    label: "Install"
